// Code generated by gen.py. DO NOT EDIT.

package expconf

import (
	"github.com/santhosh-tekuri/jsonschema/v2"

	"github.com/determined-ai/determined/master/pkg/schemas"
)

func (l LogPolicyV0) Type() LogPolicyType {
	return l.RawType
}

func (l *LogPolicyV0) SetType(val LogPolicyType) {
	l.RawType = val
}

func (l LogPolicyV0) ParsedSchema() interface{} {
	return schemas.ParsedLogPolicyV0()
}

func (l LogPolicyV0) SanityValidator() *jsonschema.Schema {
	return schemas.GetSanityValidator("http://determined.ai/schemas/expconf/v0/log-policy.json")
}

func (l LogPolicyV0) CompletenessValidator() *jsonschema.Schema {
	return schemas.GetCompletenessValidator("http://determined.ai/schemas/expconf/v0/log-policy.json")
}
